apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-app
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
            namespace: dev
          - cluster: https://kubernetes.default.svc
            namespace: staging
          - cluster: https://kubernetes.default.svc
            namespace: prod
  template:
    metadata:
      name: '{{cluster}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/4hebek/argocd-test
        path: .
        targetRevision: HEAD
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
