apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  custom.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            return 200 'Hello from custom NGINX!';
            add_header Content-Type text/plain;
        }
    }
