apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: check-health
        image: busybox
        command: ["sh", "-c", "echo Checking cluster health..."]
      restartPolicy: Never
