apiVersion: v1
kind: Service
metadata:
  name: nginx-v2
spec:
  selector:
    app: nginx
    version: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Exposed on the host machine
    type: NodePort
